---
- hosts: all
  user: root
  tasks:
  - name: Disable Firewall
    service: name=firewalld state=stopped enabled=false
  - name: Disable SELinux
    selinux: state=disabled
  - name: Create BTRFS mountpoints
    file: path={{ item }} state=directory
    with_items:
    - /opt/serviced/var/volumes
    - /var/lib/docker
  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
    - ntp
    - dnsmasq
    - http://get.zenoss.io/yum/zenoss-repo-1-1.x86_64.rpm
  - name: Install Zenoss Core Service
    yum: name=zenoss-core-service enablerepo=zenoss-stable
  - name: Enable services
    service: name={{ item }} state=running enabled=true
    with_items:
    - ntpd
    - dnsmasq
    - docker
